name = "web-xizoa-v2-admin"
main = "functions/_middleware.ts"
compatibility_date = "2026-08-10"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "xizoa-db"
database_id = "79f79c93-f3b5-4ca3-8bdc-4a38efe9b1fb"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "xizoa-media"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "28347f7e611e4d68a2e906126aae9126"

[[kv_namespaces]]
binding = "KV_RATE_LIMIT"
id = "48206b1b81634a0f978c869981442919"

[vars]
GITHUB_ALLOWED_USER = "Priyanshu maurya"
GITHUB_REPO_OWNER = "Priyanshu maurya"
GITHUB_REPO_NAME = "web-xizoa-v2"
GITHUB_BRANCH = "main"
CLOUDFLARE_ACCOUNT_ID = "f6425ef2f5876635b9742f5ddb854d4f"
CLOUDFLARE_PAGES_PROJECT = "web-xizoa-v2-admin"
R2_BUCKET = "xizoa-media"

# Secrets (yeh wrangler.toml mein nahi likhne — sirf Cloudflare Dashboard mein add karne):
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# GITHUB_TOKEN
# CLOUDFLARE_API_TOKEN
# SESSION_SECRET
# CSRF_SECRET
# ENCRYPTION_KEY

pages_build_output_dir = "dist"

[triggers]
crons = ["* * * * *"]
